include::page$attributes.adoc[]
[[dependencies]]
= Dependencies

Due to the different inception dates of individual Spring Data modules, most of them carry different major and minor version numbers. The easiest way to find compatible ones is to rely on the Spring Data Release Train BOM that we ship with the compatible versions defined. In a Maven project, you would declare this dependency in the `<dependencyManagement />` section of your POM, as follows:

.Using the Spring Data release train BOM
====
[source, xml, subs="+attributes"]
----
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>org.springframework.data</groupId>
      <artifactId>spring-data-releasetrain</artifactId>
      <version>{releasetrainVersion}</version>
      <scope>import</scope>
      <type>pom</type>
    </dependency>
  </dependencies>
</dependencyManagement>
----
====

[[dependencies.train-names]]
The current release train version is `{releasetrainVersion}`. The train names ascend alphabetically and the currently available trains are listed https://github.com/spring-projects/spring-data-commons/wiki/Release-planning[here]. The version name follows the following pattern: `${name}-${release}`, where release can be one of the following:

* `BUILD-SNAPSHOT`: Current snapshots
* `M1`, `M2`, and so on: Milestones
* `RC1`, `RC2`, and so on: Release candidates
* `RELEASE`: GA release
* `SR1`, `SR2`, and so on: Service releases

A working example of using the BOMs can be found in our https://github.com/spring-projects/spring-data-examples/tree/master/bom[Spring Data examples repository]. With that in place, you can declare the Spring Data modules you would like to use without a version in the `<dependencies />` block, as follows:

.Declaring a dependency to a Spring Data module
====
[source, xml]
----
<dependencies>
  <dependency>
    <groupId>org.springframework.data</groupId>
    <artifactId>spring-data-jpa</artifactId>
  </dependency>
<dependencies>
----
====

